SPK_NAME = monkeysaudio
SPK_VERS = 1.0
SPK_REV = 1
SPK_ICON = src/mac.png

DEPENDS = cross/monkeysaudio

MAINTAINER = SynoCommunity
DESCRIPTION = This is a port of Monkey's Audio Codec to Unix-like systems
RELOAD_UI = no
DISPLAY_NAME = monkey\'s audio
STARTABLE = no


HOMEPAGE   = https://github.com/fernandotcl/monkeys-audio
LICENSE    = https://github.com/fernandotcl/monkeys-audio/blob/master/LICENSE

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
