SPK_NAME = lame
SPK_VERS = 3.100
SPK_REV = 1
SPK_ICON = src/lame.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = High quality MPEG Audio Layer III encoder.
RELOAD_UI = no
DISPLAY_NAME = lame
STARTABLE = no

HOMEPAGE   = http://lame.sourceforge.net/
LICENSE    = LGPL

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
