SPK_NAME = cuetools
SPK_VERS = 1.4.1
SPK_REV = 1
SPK_ICON = src/cuetools.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = cuetools is a set of utilities for working with Cue Sheet (cue) and Table of Contents (toc) files.
RELOAD_UI = no
DISPLAY_NAME = cuetools
STARTABLE = no


HOMEPAGE   = https://github.com/svend/cuetools
LICENSE    = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
