SPK_NAME = flac
SPK_VERS = 1.3.2
SPK_REV = 0
SPK_ICON = src/flac.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Free Lossless Audio Codec.
RELOAD_UI = no
DISPLAY_NAME = flac
STARTABLE = no
CHANGELOG = "comments"

HOMEPAGE   = http://flac.sourceforge.net/
LICENSE    = GPL

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
