SPK_NAME = id3
SPK_VERS = 0.80
SPK_REV = 0
SPK_ICON = src/id3.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = id3 mass tagger is a tool for manipulating id3 and id3v2 tags in multiple files.
RELOAD_UI = no
DISPLAY_NAME = id3
STARTABLE = no


HOMEPAGE   = https://squell.github.io/id3
LICENSE    = https://github.com/squell/id3/blob/master/COPYING

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
