SPK_NAME = libiconv
SPK_VERS = 1.15
SPK_REV = 1
SPK_ICON = src/libiconv.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = This library provides an iconv() implementation, for use on systems which don't have one, or whose implementation cannot convert from/to Unicode. 
RELOAD_UI = no
DISPLAY_NAME = libiconv
STARTABLE = no


HOMEPAGE   = https://www.gnu.org/software/libiconv
LICENSE    = GNU GPLv3

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
