SPK_NAME = file
SPK_VERS = 5.35
SPK_REV = 1
SPK_ICON = src/file.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = The file command is "a file type guesser", that is, a command-line tool that tells you in words what kind of data a file contains.
RELOAD_UI = no
DISPLAY_NAME = file
STARTABLE = no


HOMEPAGE   = http://www.darwinsys.com/file
LICENSE    = https://github.com/file/file/blob/master/COPYING

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
