SPK_NAME = shntool
SPK_VERS = 3.0.10
SPK_REV = 1
SPK_ICON = src/shntool.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = shntool is a multi-purpose WAVE data processing and reporting utility that supports various lossless audio formats.
RELOAD_UI = no
DISPLAY_NAME = shntool
STARTABLE = no


HOMEPAGE   = https://github.com/flacon/shntool
LICENSE    = GPL

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

include ../../mk/spksrc.spk.mk
